# Generated by Django 4.2.3 on 2023-08-01 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_question_author_userquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestion',
            new_name='Vote',
        ),
    ]
